server {
    listen 80;
    listen [::]:80;
    server_name my-projects.javohir-dev.uz;
    location ^~ /.well-known/acme-challenge/ { root /var/www/my-projects-acme; }
    location / { return 301 https://$host$request_uri; }
}
